language: python
python:
  - "3.5"
# command to install dependencies
install: "pip install -r requirements/local.txt"
# command to run tests
script:
  - cp camper/settings/travis.py camper/settings/local.py
  - nosetests
