db:
  image: postgres
  env_file: secrets.env
  # TODO mount volume - PGDATA or /var/lib/postgresql/data
rabbitmq:
  image: rabbitmq
  env_file: secrets.env
web:
  build: .
  command: gunicorn -w 3 -b 0.0.0.0 camper.wsgi
  restart: always
  ports:
    - "8000:8000"
  links:
    - db
    - rabbitmq
  env_file: secrets.env

# TODO Celery worker
# TODO ngnix
